app/urls.py
from django.views.i18n import javascript_catalog
from django.conf.urls import url
from app.views import *

urlpatterns = [
    url(r'user/(?P<user_id>\d+)/profile/$', user_profile, name='user-profile'),
    url(r'user/(?P<user_id>\d+)/profile/settings/$', profile_settings, name='profile-settings'),
    url(r'publications/', get_publications, name='publications'),
    url(r'updatePhoto/', UpdatePhoto.as_view()),
    url(r'getProfile/', GetProfile.as_view()),
    url(r'createpublication/(?P<template_id>\d+)/change/(?P<prev_id>\d+)/$', AddPublication.as_view(),
        name='create-publication'),
    url(r'getTags/', GetTags.as_view()),
    url(r'makepublication/', MakePublication.as_view(), name='edit'),
    url(r'createcomment/', CreateComment.as_view(), name='create-comment'),
    url(r'articles/(?P<publication_id>\d+)/$', ShowPublication.as_view(), name='show'),
    url(r'comments/', GetComments.as_view(), name='comments'),
    url(r'vote/', VotesController.as_view(), name='vote'),
    url(r'search/', MySearchView(), name='search'),
    url(r'deletePublication/(?P<publication_id>\d+)/$', DeletePublication.as_view(), name='delete'),
    url(r'deleteComment/(?P<comment_id>\d+)/$', DeleteComment.as_view()),
    url(r'^jsi18n/$', javascript_catalog),
]

courseproject/urls.py
from django.conf.urls import url, patterns, include
from django.contrib import admin
from app.views import *
from authenticating.views import acquire_email
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^$', home, name='home'),
                  url(r'', include('authenticating.urls')),
                  url(r'', include('app.urls')),
                  url(r'^emailrequired/', acquire_email, name='acquire_email'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

app/models.py
from django.db import models
from tagging.fields import TagField

from courseproject import settings
from courseproject.models import Category, Template


class Publication(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    category = models.ForeignKey(Category)
    header = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False, blank=True)
    body = models.TextField()
    tag = TagField()
    template = models.ForeignKey(Template)
    image = models.URLField(blank=True)

    def __str__(self):
        return self.header + u'. Author: %s' % self.author

    def calculate_rate(self):
        return PublicationVote.objects.filter(target_id=self, like=True).count() - PublicationVote.objects.filter(
                target_id=self, like=False).count()


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    publication = models.ForeignKey(Publication)
    text = models.CharField(max_length=500)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False, blank=True)

    def __str__(self):
        return u'. Comment to: %s' % self.publication.header + u'. Author: %s' % self.author

    def calculate_rate(self):
        return CommentVote.objects.filter(target_id=self, like=True).count() - CommentVote.objects.filter(
                target_id=self, like=False).count()


class PublicationVote(models.Model):
    like = models.BooleanField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    target = models.ForeignKey(Publication)


class CommentVote(models.Model):
    like = models.BooleanField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    target = models.ForeignKey(Comment)


class Achievement(models.Model):
    name = models.CharField(max_length=15, unique=True)
    description = models.CharField(max_length=200, default="")
    picture = models.URLField()


class UsersAchievement(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    achievement = models.ForeignKey(Achievement)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True)

authenticating/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils import timezone

from app.models import PublicationVote, CommentVote, Publication, Comment, Achievement, UsersAchievement
from courseproject.models import Theme, Language


# Create your models here.

class AccountManager(BaseUserManager):
    def create_user(self, username, email, password=None, **kwargs):
        if not username:
            raise ValueError('Users must have a valid username.')

        if not email:
            raise ValueError('Users must have a valid email address.')

        account = self.model(username=username, email=self.normalize_email(email))

        account.set_password(password)
        account.save()
        return account

    def create_superuser(self, username, email, password, **kwargs):
        account = self.create_user(username, email, password, **kwargs)

        account.is_admin = True
        account.save()

        return account


class Account(AbstractBaseUser):
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=50, blank=True, unique=True)
    location = models.CharField(max_length=50, blank=True)
    gender = models.CharField(max_length=10, blank=True)
    about = models.CharField(max_length=100, blank=True)
    photo = models.URLField(blank=True)
    theme = models.ForeignKey(Theme, default=1)
    language = models.ForeignKey(Language, default=1)
    is_admin = models.BooleanField(default=False)
    is_banned = models.BooleanField(default=False)
    karma = models.IntegerField(default=0)

    created_at = models.DateTimeField(default=timezone.now, editable=False, blank=True)
    updated_at = models.DateTimeField(default=timezone.now, editable=False, blank=True)

    objects = AccountManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    @property
    def is_superuser(self):
        return self.is_admin

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_active(self):
        return not self.is_banned

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    def calculate_rate(self):
        rate = PublicationVote.objects.filter(like=True, target__author=self.id).count()
        rate += CommentVote.objects.filter(like=True, target__author=self.id).count()
        rate -= PublicationVote.objects.filter(like=False, target__author=self.id).count()
        rate -= CommentVote.objects.filter(like=False, target__author=self.id).count()
        return rate

    def set_achievement(self, name):
        return UsersAchievement.objects.get_or_create(user=self, achievement=Achievement.objects.get(name=name))

templates/Template1.html
{% load i18n %}

<div class="article">
    <div id="img1templ" class="col-lg-6 col-md-6 pull-left">
        <img ng-show="!'{{ publication.image }}'" id="target" style="max-height: 400px;" class="img-thumbnail"
             src="http://placehold.it/600x400">
        <img ng-show="{{ publication.image }}" style="max-height: 400px;" class="img-thumbnail"
             src="{{ publication.image }}">
    </div>
    <div class="col-md-6 pull-right">
        <ul class="breadcrumb">
            <li>{% verbatim %}{{ ctrl.category }}{% endverbatim %} {% trans publication.category.name %}</li>
            <li><span class="label label-success">
                {% if publication.id %}
                    <a href={% url 'user-profile' author_id %}>{% verbatim %}{{ ctrl.author }}{% endverbatim %} {{ publication.author }}</a>
                {% else %}
                    <span>{% verbatim %}{{ ctrl.author }}{% endverbatim %} {{ publication.author }}</span>
                {% endif %}
            </span></li>
            <li class="active">{% verbatim %}{{ ctrl.date | date:'medium' }}{% endverbatim %}
                {{ publication.created_at }}</li>
            <span class="pull-right"
                  ng-show="{{ author_id }}== {{ request.user.id }} || '{{ is_super }}' == 'True' ">
                {% if publication.id %}
                    <a href="{% url 'delete' publication.id %}">
                {% else %}
                    <a href="">
                {% endif %}
                <i style="font-size: 25px; color:#e74c3c; margin-left: 5px" class="fa fa-times "></i></a></span>
            <span class="pull-right" ng-show="{{ author_id }}== {{ request.user.id }} || '{{ is_super }}' == 'True' ">
                {% if publication.id %}
                    <a href="{% url 'create-publication' publication.template.id publication.id %}">
                {% else %}
                    <a href="">
                {% endif %}
                <i style="font-size: 25px; color: #3498db;" class="fa fa-pencil "></i></a></span>

        </ul>
    </div>

    <div class="content text-left">
        <h1 class="text-center">{% verbatim %}{{ ctrl.header }}{% endverbatim %}{{ publication.header }}</h1>
        <div id="content" ng-bind-html="ctrl.htmlcontent"></div>
        {{ publication.body | safe }}
    </div>
</div>

templates/Template2.html
{% load i18n %}

<div class="article">
    <div class="col-lg-12 col-md-12">
        <ul class="breadcrumb">
            <li>{% verbatim %}{{ ctrl.category }}{% endverbatim %} {% trans publication.category.name %}</li>
            <li><span class="label label-success">
                {% if publication.id %}
                    <a href={% url 'user-profile' author_id %}>{% verbatim %}{{ ctrl.author }}{% endverbatim %} {{ publication.author }}</a>
                {% else %}
                    <span>{% verbatim %}{{ ctrl.author }}{% endverbatim %} {{ publication.author }}</span>
                {% endif %}
            </span></li>
            <li class="active">{% verbatim %}{{ ctrl.date | date:'medium' }}{% endverbatim%}
                {{ publication.created_at }}</li>
            <span class="pull-right"
                  ng-show="{{ author_id }}== {{ request.user.id }} || '{{ is_super }}' == 'True' ">
                {% if publication.id %}
                    <a href="{% url 'delete' publication.id %}">
                {% else %}
                    <a href="">
                {% endif %}
                <i style="font-size: 25px; color:#e74c3c; margin-left: 5px" class="fa fa-times "></i></a></span>
            <span class="pull-right" ng-show="{{ author_id }}== {{ request.user.id }} || '{{ is_super }}' == 'True' ">
                {% if publication.id %}
                    <a href="{% url 'create-publication' publication.template.id publication.id %}">
                {% else %}
                    <a href="">
                {% endif %}
                <i style="font-size: 25px; color: #3498db; margin-left: 5px" class="fa fa-pencil "></i></a></span>
        </ul>
    </div>
    <h1 class="text-center">{% verbatim %}{{ ctrl.header }}{% endverbatim %}{{ publication.header }}</h1>
    <div class="col-lg-12 col-md-12">
        <div class="text-center" style="margin-bottom: 10px">
            <img id="target" ng-show="!'{{ publication.image }}'" style="max-height: 240px"
                 class="img-responsive img-thumbnail" src="http://placehold.it/1024x240">
            <span ng-show="{{ publication.image }}" class="imgRect2 img-thumbnail"
                  style="background-image: url({{ publication.image }}); height: 240px;"></span>
            </span>
        </div>
    </div>

    <div class="content text-left">
        <div id="content" ng-bind-html="ctrl.htmlcontent"></div>
        {{ publication.body | safe }}
    </div>

</div>

templates/Template3.html
{% load i18n %}

<div class="article">
    <div class="col-md-12">
        <ul class="breadcrumb">
            <li>{% verbatim %}{{ ctrl.category }}{% endverbatim %} {% trans publication.category.name %}</li>
            <li><span class="label label-success">
                {% if publication.id %}
                    <a href={% url 'user-profile' author_id %}>{% verbatim %}{{ ctrl.author }}{% endverbatim %} {{ publication.author }}</a>
                {% else %}
                    <span>{% verbatim %}{{ ctrl.author }}{% endverbatim %} {{ publication.author }}</span>
                {% endif %}
            </span></li>
            <li class="active">{% verbatim %}{{ ctrl.date | date:'medium' }}{% endverbatim %}
                {{ publication.created_at }}</li>
            <span class="pull-right"
                  ng-show="{{ author_id }}== {{ request.user.id }} || '{{ is_super }}' == 'True' ">
                {% if publication.id %}
                    <a href="{% url 'delete' publication.id %}">
                {% else %}
                    <a href="">
                {% endif %}
                <i style="font-size: 25px; color:#e74c3c; margin-left: 5px" class="fa fa-times "></i></a></span>
            <span class="pull-right" ng-show="{{ author_id }}== {{ request.user.id }} || '{{ is_super }}' == 'True' ">
                {% if publication.id %}
                    <a href="{% url 'create-publication' publication.template.id publication.id %}">
                {% else %}
                    <a href="">
                {% endif %}
                <i style="font-size: 25px; color: #3498db;" class="fa fa-pencil "></i></a></span>
        </ul>
    </div>
    <div class="col-md-12 content text-left">
        <h1 class="text-center">{% verbatim %}{{ ctrl.header }}{% endverbatim %}{{ publication.header }}</h1>
        <div id="content" ng-bind-html="ctrl.htmlcontent"></div>
        {{ publication.body | safe }}
    </div>
</div>

templates/article.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="col-md-12">
        {% include template %}
    </div>
    <div ng-controller="CommentsController as ctrl"
         ng-init="ctrl.init('{{ publication.id }}', '{{ request.user.username }}', '{{ is_super }}', {{ publication.rate }},'{{ like }}')"
         class="col-md-12" id="commentsblock">
        <div class="col-md-2 well well-sm text-center">
            <span style="padding-right: 10px">
                {% verbatim %}
                <span ng-show="ctrl.rate > 0" class="badge plus">+{{ ctrl.rate }}</span>
                <span ng-show="ctrl.rate == 0" class="badge nul">{{ ctrl.rate }}</span>
                <span ng-show="ctrl.rate < 0" class="badge minus">{{ ctrl.rate }}</span>
                {% endverbatim %}
            </span>
            {% if user.is_authenticated %}

                <a href="" ng-click="ctrl.vote(0,'True',ctrl.publication_id)" ng-cloak
                   ng-hide="(ctrl.like == true)"><i style="font-size: 18px; color: #18bc9c; padding-right: 3px"
                                                    class="fa fa-thumbs-up"></i></a>
                <a href="" ng-click="ctrl.vote(0,'True',ctrl.publication_id)" ng-cloak
                   ng-show="(ctrl.like == true)"><i style="font-size: 25px; color: #e74c3c; padding-right: 3px"
                                                    class="fa fa-thumbs-up"></i></a>
                <a href="" ng-click="ctrl.vote(0,'False', ctrl.publication_id)" ng-cloak
                   ng-hide="(ctrl.like == false)"><i style="font-size: 18px; color: #18bc9c;"
                                                     class="fa fa-thumbs-down"></i></a>
                <a href="" ng-click="ctrl.vote(0,'False',ctrl.publication_id)" ng-cloak
                   ng-show="(ctrl.like == false)"><i style="font-size: 25px; color: #e74c3c;"
                                                     class="fa fa-thumbs-down"></i></a>

            {% endif %}
        </div>
        <div class="col-md-8">

            <div ng-repeat="comment in ctrl.comments track by $index" class="comment panel panel-default">
                {% verbatim %}
                <div class="panel-body">
                    <p ng-hide="ctrl.isEdit && ctrl.editindex == $index">{{ comment.text }}</p>
                    <textarea ng-model="ctrl.editcomment" ng-show="ctrl.isEdit && ctrl.editindex == $index" id="edit"
                              type="text" class="form-control" maxlength="500" name="edit">{{ comment.text }}</textarea>
                </div>
                <div class="panel-footer">
                    <ul class="breadcrumb">
                        <li>
                        <span id="userpicnavbar">
                            <span class="imgRect" style="background-image: url({{ comment.pic }})"></span>
                        </span>
                            <span class="label label-success"><a href="/user/{{ comment.author_id }}/profile/">{{
                                comment.author}}</a></span>
                        </li>
                        <li class="active"><span>{{ comment.created_at | date:'medium'}}</span></li>
                        <li>
                            <span ng-show="comment.rate > 0" class="badge plus">+{{ comment.rate }}</span>
                            <span ng-show="comment.rate == 0" class="badge nul">{{ comment.rate }}</span>
                            <span ng-show="comment.rate < 0" class="badge minus">{{ comment.rate }}</span>
                        </li>
                        {% endverbatim %}

                        {% if user.is_authenticated %}
                            <li>
                                {% verbatim %}
                                <a href="" ng-click="ctrl.vote(comment.id,'True')" ng-cloak
                                   ng-hide="(comment.like == true)"><i style="font-size: 18px; color: #18bc9c;"
                                                                       class="fa fa-thumbs-up"></i></a>
                                <a href="" ng-click="ctrl.vote(comment.id,'True')" ng-cloak
                                   ng-show="(comment.like == true)"><i style="font-size: 25px; color: #e74c3c;"
                                                                       class="fa fa-thumbs-up"></i></a>
                                <a href="" ng-click="ctrl.vote(comment.id,'False')" ng-cloak
                                   ng-hide="(comment.like == false)"><i style="font-size: 18px; color: #18bc9c;"
                                                                        class="fa fa-thumbs-down"></i></a>
                                <a href="" ng-click="ctrl.vote(comment.id,'False')" ng-cloak
                                   ng-show="(comment.like == false)"><i style="font-size: 25px; color: #e74c3c;"
                                                                        class="fa fa-thumbs-down"></i></a>
                                {% endverbatim %}
                            </li>
                        {% endif %}
                        {% verbatim %}
                        <span class="pull-right"
                              ng-show="comment.author ==  ctrl.username  ||  ctrl.is_super  == 'True' ">
                            <a href="" ng-click="ctrl.deleteComment(comment.id)">
                                <i style="font-size: 25px; color:#e74c3c; padding-left: 10px"
                                   class="fa fa-ban "></i></a></span>
                        <span ng-show=" comment.author ==  ctrl.username  ||  ctrl.is_super  == 'True' ">
                            <a ng-hide="ctrl.isEdit && ctrl.editindex == $index"
                               ng-click="ctrl.edit(true, false, comment.text, $index, comment.id)" href=""><i
                                    style="font-size: 25px; color: #3498db;" class="fa fa-pencil pull-right"></i></a>
                            <a ng-show="ctrl.isEdit && ctrl.editindex == $index"
                               ng-click="ctrl.edit(false, true, comment.text, $index, comment.id)" href=""><i
                                    style="font-size: 25px; color: #18bc9c;" class="fa fa-check pull-right"></i></a>
                            <a ng-show="ctrl.isEdit && ctrl.editindex == $index"
                               ng-click="ctrl.edit(false, false, comment.text, $index, comment.id)" href=""><i
                                    style="font-size: 25px; color: #e74c3c;" class="fa fa-times pull-right"></i></a>

                        </span>
                        {% endverbatim %}
                    </ul>

                </div>

            </div>
            {% if user.is_authenticated %}
                <form class="form-horizontal" method="post" action="{% url 'create-comment' %}">
                    {% csrf_token %}
                    <div class="comment panel panel-default">
                        <div class="panel-body">
                        <textarea id="text" ng-model="ctrl.text" ng-change="ctrl.inputChange('#text')" type="text"
                                  class="form-control" maxlength="500" name="text"
                                  placeholder="{% trans 'say something' %}">
                        </textarea>
                        </div>
                        <div class="panel-footer">
                            <ul class="breadcrumb">
                                <li>
                        <span id="userpicnavbar">
                            <span class="imgRect" style="background-image: url({{ user.photo }})"></span>
                        </span>
                                    <span class="label label-success"><a
                                            href="/user/{{ user.id }}/profile/">{{ user.username }}</a></span>
                                </li>
                                <a ng-disabled="ctrl.isBlank" ng-click="ctrl.submit('{{ publication.id }}')"
                                   class="btn btn-danger pull-right">{% trans 'send' %}</a>
                                {#                            type="submit"#}
                            </ul>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load i18n %}
{% load static from staticfiles %}
{% block content %}
    <div ng-controller="PreviewController as ctrl"
         ng-init="ctrl.initPreview('#content','#dropview','#target',{{ prev_data }},'{{ request.user.username }}')">
        <div {% if request.user.theme.id == 1 %} style="background-color: #ffffff" {% else %} style="background-color: #222222" {% endif %} class="collapse" id="previewzona">
            {% include template %}
        </div>
        <form class="form-horizontal">
            {% csrf_token %}
            <div class="col-md-offset-1 col-md-11" id="formzona">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-2">
                            <label for="id_header" class=" control-label">{% trans 'Header' %}:</label>
                        </div>
                        <div class="col-md-6">
                            <input ng-model="ctrl.header" ng-change="ctrl.inputChange('#id_header', 0)" ng-trim="false"
                                   type="text" class="form-control" id="id_header"
                                   maxlength="100" name="header" placeholder="{% trans 'you header' %}"/>
                        </div>
                    </div>

                    <div id="id_description_tab" class="form-group">
                        <div class="col-md-2">
                            <label for="id_description" class=" control-label">{% trans 'Description' %}:</label>
                        </div>
                        <div class="col-md-6">
                <textarea ng-change="ctrl.inputChange('#id_description', 1)" ng-trim="false" ng-model="ctrl.description"
                          class="form-control" id="id_description" type="text"
                          name="description" placeholder="{% trans 'you description' %}" maxlength="500"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-2">
                            <label for="id_category" class=" control-label">{% trans 'Category' %}:</label>
                        </div>
                        <div class="col-md-6 selectlist">
                            <select ng-model="ctrl.category" id="id_category" class="form-control col-md-6" size="1"
                                    name="category">
                                {% for val in catlist %}
                                    <option
                                            value="{{ val.name }}">{% trans val.name %}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-2">
                            <label for="id_tags" class=" control-label">{% trans 'Tags' %}:</label>
                        </div>
                        <div class="col-md-6">
                            <tags-input required name="tags" ng-model="ctrl.tags"
                                        id="id_tags" max-length="15"
                                        min-tags="3"
                                        max-tags="5"
                                        placeholder="{% trans 'three at least, five maximum' %}"
                                        on-tag-removed="ctrl.checkTags()"
                                        on-tag-added="ctrl.checkTags()">
                                <auto-complete source="ctrl.loadTags($query)"></auto-complete>
                            </tags-input>
                        </div>
                    </div>

                </div>
                <span class="col-md-6">
                    <div ng-hide="'{{ template_id }}'==3" id="dropview"
                         class="dropzona col-md-8 btn btn-default btn-file">
                        <br>
                        <br>
                        <br>
                        <span class="glyphicon glyphicon-camera"></span>
                        <span>{% trans 'drop your images here' %}</span>
                        <input id="id_photo" name="photo" type="file" accept="image/*"
                               on-read-file="ctrl.fillFileFromInput()">
                    </div>
                </span>
            </div>

            <div class="col-md-12" id="editzona">
                <textarea ng-trim="false" name="editor" id="editor" rows="10" cols="80">
                    {% trans 'Your text will de shown here. Just remove this one and start to type in editor' %}
                </textarea>
                <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
                <script src="{% static 'ckeditor/styles.js' %}"></script>
                <script src="{% static 'ckeditor/config.js' %}"></script>
                <script src="{% static 'ckeditor/lang/ru.js' %}"></script>
                <script src="{% static 'ckeditor/lang/en.js' %}"></script>
                <script src="{% static 'ckeditor/plugins/wenzgmap/dialogs/wenzgmap.js' %}"></script>
                <script src="{% static 'ckeditor/plugins/link/dialogs/link.js' %}"></script>
                <script src="{% static 'ckeditor/plugins/link/dialogs/anchor.js' %}"></script>
                <script src="{% static 'ckeditor/plugins/tliyoutube2/dialogs/tliyoutube2.js' %}"></script>
                <script src="{% static 'ckeditor/plugins/SimpleImage/dialogs/simpleimage.js' %}"></script>
                <script src="{% static 'ckeditor/plugins/SimpleLink/dialogs/simplelink.js' %}"></script>
                <script src="{% static 'ckeditor/plugins/videodetector/dialogs/videoDialog.js' %}"></script>
                <link rel="stylesheet" href="{% static 'styles/ckeditor.css' %}" type="text/css">
                <link rel="stylesheet" href="{% static 'ckeditor/skins/bootstrapck/dialog.css' %}" type="text/css">
                <script>
                    CKEDITOR.replace('editor', {
                        language: '{{ user.language.code }}'
                    });

                </script>
                <div class="editbuttongroup col-md-12">
                    <div class="col-md-4" ng-show="!ctrl.sending">
                        <a href="#" class="btn btn-danger">{% trans 'Cancel' %}</a>
                        <a ng-click="ctrl.ShowPublication()" data-toggle="collapse"
                           data-target="#previewzona" class="btn btn-warning">{% trans 'Preview' %}</a>
                        <a class="btn btn-success"
                           ng-disabled="ctrl.isBlank[0] || ctrl.isBlank[1] || ctrl.sending || ctrl.tagIncorrect"
                           ng-click="ctrl.submit({{ template_id }})">{% trans 'Publish' %}</a>
                    </div>
                    <div class="col-md-12">
                        <div style="margin-top: 10px" ng-cloak ng-show="ctrl.sending"
                             class="progress progress-striped active">
                            <div class="progress-bar" style="width: 100%">{% trans 'loading ' %}</div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}