app/urls.py
from django.views.i18n import javascript_catalog
from django.conf.urls import url
from app.views import *

urlpatterns = [
    url(r'user/(?P<user_id>\d+)/profile/$', user_profile, name='user-profile'),
    url(r'user/(?P<user_id>\d+)/profile/settings/$', profile_settings, name='profile-settings'),
    url(r'publications/', get_publications, name='publications'),
    url(r'updatePhoto/', UpdatePhoto.as_view()),
    url(r'getProfile/', GetProfile.as_view()),
    url(r'createpublication/(?P<template_id>\d+)/change/(?P<prev_id>\d+)/$', AddPublication.as_view(),
        name='create-publication'),
    url(r'getTags/', GetTags.as_view()),
    url(r'makepublication/', MakePublication.as_view(), name='edit'),
    url(r'createcomment/', CreateComment.as_view(), name='create-comment'),
    url(r'articles/(?P<publication_id>\d+)/$', ShowPublication.as_view(), name='show'),
    url(r'comments/', GetComments.as_view(), name='comments'),
    url(r'vote/', VotesController.as_view(), name='vote'),
    url(r'search/', MySearchView(), name='search'),
    url(r'deletePublication/(?P<publication_id>\d+)/$', DeletePublication.as_view(), name='delete'),
    url(r'deleteComment/(?P<comment_id>\d+)/$', DeleteComment.as_view()),
    url(r'^jsi18n/$', javascript_catalog),
]

courseproject/urls.py
from django.conf.urls import url, patterns, include
from django.contrib import admin
from app.views import *
from authenticating.views import acquire_email
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^$', home, name='home'),
                  url(r'', include('authenticating.urls')),
                  url(r'', include('app.urls')),
                  url(r'^emailrequired/', acquire_email, name='acquire_email'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

authenticating/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils import timezone

from app.models import PublicationVote, CommentVote, Publication, Comment, Achievement, UsersAchievement
from courseproject.models import Theme, Language


# Create your models here.

class AccountManager(BaseUserManager):
    def create_user(self, username, email, password=None, **kwargs):
        if not username:
            raise ValueError('Users must have a valid username.')

        if not email:
            raise ValueError('Users must have a valid email address.')

        account = self.model(username=username, email=self.normalize_email(email))

        account.set_password(password)
        account.save()
        return account

    def create_superuser(self, username, email, password, **kwargs):
        account = self.create_user(username, email, password, **kwargs)

        account.is_admin = True
        account.save()

        return account


class Account(AbstractBaseUser):
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=50, blank=True, unique=True)
    location = models.CharField(max_length=50, blank=True)
    gender = models.CharField(max_length=10, blank=True)
    about = models.CharField(max_length=100, blank=True)
    photo = models.URLField(blank=True)
    theme = models.ForeignKey(Theme, default=1)
    language = models.ForeignKey(Language, default=1)
    is_admin = models.BooleanField(default=False)
    is_banned = models.BooleanField(default=False)
    karma = models.IntegerField(default=0)

    created_at = models.DateTimeField(default=timezone.now, editable=False, blank=True)
    updated_at = models.DateTimeField(default=timezone.now, editable=False, blank=True)

    objects = AccountManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    @property
    def is_superuser(self):
        return self.is_admin

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_active(self):
        return not self.is_banned

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    def calculate_rate(self):
        rate = PublicationVote.objects.filter(like=True, target__author=self.id).count()
        rate += CommentVote.objects.filter(like=True, target__author=self.id).count()
        rate -= PublicationVote.objects.filter(like=False, target__author=self.id).count()
        rate -= CommentVote.objects.filter(like=False, target__author=self.id).count()
        return rate

    def set_achievement(self, name):
        return UsersAchievement.objects.get_or_create(user=self, achievement=Achievement.objects.get(name=name))

app/templates/profile_settings.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block content %}

    <div ng-controller="PhotoUploader as ctrl" ng-init="ctrl.init('#dropZone','#photo')">
        <div class="col-md-4 col-md-offset-1">
            <div id="photoitem">
                <img id="photo" class="img-responsive img-thumbnail" src="{{ user.photo }}"
                     on-src-changed="ctrl.inverseParameterChanged()"/>
            </div>
            <div ng-cloak ng-show="ctrl.changed">
                <button class="btn btn-danger" ng-click="ctrl.cancelChange()">{% trans 'Cancel' %}</button>
                <button class="btn btn-success" ng-click="ctrl.applyChange()">{% trans 'Apply' %}</button>
            </div>
            <div ng-cloak ng-show="ctrl.inLoading" class="progress progress-striped active">
                <div class="progress-bar" style="width: 100%">{% trans 'loading ' %}</div>
            </div>
                <span id="dropZone" ng-cloak ng-show="!ctrl.inLoading && !ctrl.changed"
                      class=" dropzona col-md-12 col-xs-12 btn btn-default btn-file">
                    <span>
                        <br>
                        <br>
                        <span class="glyphicon glyphicon-camera"></span>
                        {% trans 'cliсk or drop image here' %}
                    </span>
                    <input id="id_photo" name="photo" type="file" accept="image/*"
                           on-read-file="ctrl.fillFileFromInput()">
                </span>
        </div>
    </div>


    <form class="form-horizontal" method="post" action="{% url 'profile-settings' user.id %}"
          enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="col-md-5">
            <div class="form-group">
                <label for="id_username" class="col-lg-4 control-label">{% trans 'User' %}:</label>
                <div class="col-lg-8">
                    <input type="text" disabled class="form-control" id="id_username" maxlength="20"
                           name="username"
                           placeholder="{% trans 'User' %}" value="{{ user.username }}"/>
                </div>
            </div>

            <div class="form-group">
                <label for="id_email" class="col-lg-4 control-label">Email:</label>
                <div class="col-lg-8">
                    <input class="form-control" id="id_email" disabled maxlength="50" name="email" type="email"
                           placeholder="Email" value="{{ user.email }}"/>
                </div>
            </div>

            <div class="form-group">
                <label for="id_gender" class="col-lg-4 control-label">{% trans "Gender" %}:</label>
                <div class="col-lg-8 selectlist">
                    <select class="form-control col-lg-8" size="1" name="gender">
                        {% for val in selectgender %}
                            <option value="{{ val }}"
                                    {% if val == user.gender %}
                                    selected="selected"
                                    {% elif val == 'select' %}
                                    selected="selected" disabled="disabled"
                                    {% endif %}>{% trans val %}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="id_location" class="col-lg-4 control-label">{% trans 'Location' %}:</label>
                <div class="col-lg-8">
                    <input class="form-control" id="id_location" maxlength="50" name="location"
                           placeholder="{% trans 'Location' %}" value="{{ user.location }}" type="text"/>
                </div>
            </div>

            <div class="form-group">
                <label for="id_about" class="col-lg-4 control-label">{% trans 'About' %}:</label>
                <div class="col-lg-8">
                    <textarea class="form-control" id="id_about" maxlength="100" name="about"
                              placeholder="{% trans 'About' %}">{{ user.about }}</textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="id_theme" class="col-lg-4 control-label">{% trans "Theme" %}:</label>
                <div class="col-lg-8">
                    {% for val in themes %}
                        <label class="radio-inline">
                            <input id="id_theme" type="radio" name="theme" value="{{ val.name }}"
                                    {% if val.name == user.theme.name %}
                                   checked="checked"
                                    {% endif %}/>{% trans val.name %}</label>
                    {% endfor %}
                </div>
            </div>

            <div class="form-group">
                <label for="id_language" class="col-lg-4 control-label">{% trans "Language" %}:</label>
                <div class="col-lg-8 selectlist">
                    <select id="id_language" class="form-control col-lg-8" size="1" name="language">
                        {% for val in selectlang %}
                            <option value="{{ val.name }}"
                                    {% if val.name == user.language.name %}
                                    selected="selected"
                                    {% endif %}>{% trans val.name %}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-4">
                    <a href="{% url 'home' %}" type="reset" class="btn btn-default">{% trans 'Cancel' %}</a>
                    <button type="submit" class="btn btn-primary" value="Register">OK</button>
                </div>
            </div>
        </fieldset>
    </form>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
{% endblock %}